# Must use for Qt 6.9 https://bugreports.qt.io/browse/QTBUG-135452
# https://github.com/conda-forge/opencv-feedstock/pull/465#issuecomment-2854148414
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
