# Must use for Qt 6.9 https://bugreports.qt.io/browse/QTBUG-135452
# https://github.com/conda-forge/opencv-feedstock/pull/465#issuecomment-2854148414
c_compiler:      # [win64]
  - 'vs2019'     # [win64]
  - 'vs2022'     # [win64]
cxx_compiler:    # [win64]
  - 'vs2019'     # [win64]
  - 'vs2022'     # [win64]
libopencv:       # [win64]
  - '4.10'       # [win64]
  - '4.11.0'     # [win64]
zip_keys:                     # [win64]
  - c_compiler                # [win64]
  - cxx_compiler              # [win64]
  - libopencv                 # [win64]
